# Generated by Django 3.2.13 on 2022-11-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='hits',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
