# Generated by Django 3.2.13 on 2022-11-03 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_hits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='hits',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
